### ISSUE TITLE
Are Russia, USA & Canada not countries? 👀

### ISSUE THREAD

**Issue by binakot** [TyVik/geopuzzle#1]
Why there is no Russia, USA & Canada in the game? Also Greenland is an autonomous constituent country within the Kingdom of Denmark 😉

![all-country](https://user-images.githubusercontent.com/1783893/35878049-2995d250-0b88-11e8-8355-9ebaffe7d264.png)

**Comment by TyVik** [comment]
As you can see, small countries (like Aruba, Curaçao, etc..) are not presented too. Mainly because you still can not find them, as well as the countries listed by you are too obvious :)
