### ISSUE TITLE
Change intro text

### ISSUE THREAD

**Issue by TyVik** [TyVik/geopuzzle#11]
```
Here, in the form of a game, you can learn the names and locations of each country or state and have fun doing it. In your hands are all of the regions of the world! Select a region in its proper place or from a list and see its flag and coat of arms and perhaps even more information to help you learn. Moreover, after registration you can create your own puzzles from more than 100,000 regions, as well as monitor progress.
```

**Comment by TyVik** [comment]
@RAJAGOPALAN-GANGADHARAN sure! :) This text should be on the main page instead `"It turns out that the tallest people live in Rwanda,"...`. NB about translation file, and let me know after edit - I'll update russian translation.

P.S. Please, make that changes in feature/users branch. I still have not enough time to merge it into master :(

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik not able to run it
problem while creating tables
<b>Apps are not yet  loaded</b>
please help me to fix this

**Comment by TyVik** [comment]
@RAJAGOPALAN-GANGADHARAN it's very strange... It's too general exception, could you please find which exactly not loaded (for example, comments one-by-one lines in INSTALLED_APPS)? And could you please attach stack trace, I'm not sure that it would be helpful, but it may be helpful.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik can you tell me which version of django are you using.It would be much helpful.I know i am taking a long time but i am a beginner so can you please guide me in this.

**Comment by TyVik** [comment]
Hmm... I've fixed requirements.txt in develop branch, could you please try again apply them on new clean environment? If it's fail again, attach log output for better analyze.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
![screenshot from 2018-06-10 20-55-22](https://user-images.githubusercontent.com/29299197/41203236-d56e1ae0-6cf1-11e8-8093-f817a527d146.png)
Please check the stack trace @TyVik

**Comment by TyVik** [comment]
Great! I've reproduce same problem on my desktop. You need just create new `.env` file in project root with template (`.env_template`). I updated README.md and template in develop branch. Thank you for perseverance :+1:

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik Finally did it feels like a great achievement 😆 Please review it.Thank you so much for the support want to work more on this.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik i didnt see the latest requirements before that i did the commit so please dont mind it.
