### ISSUE TITLE
The game is broken and page refresh doesn't help 🤔

### ISSUE THREAD

**Issue by karataev** [TyVik/geopuzzle#112]
![geopuzzle](https://user-images.githubusercontent.com/12277086/48311523-a3934d00-e5d3-11e8-9dda-8543ce6da7e9.jpg)

**Comment by TyVik** [comment]
К сожалению, сейчас это штатная ситуация. Показы гуглокарт стоят $7 за 1000 штук. Я превысил бесплатный лимит в 28 000 загрузок, ушёл в минус на $50 и решил отключить свой ключ. Это привело к тому, что стали появляться все эти надписи, хотя игра по-прежнему полностью работоспособна. 

Что же касается кнопки "игра сломалась!", то она позволяет обойти лишь этот баг - https://stackoverflow.com/questions/53021181/drop-a-polygon-via-js-during-users-dragndrop.

**Comment by TyVik** [comment]
Пробовал. Ответ: "Регистрируйте НКО в России, потом обращайтесь в какую-то международную организацию для подтверждения non-profit, и только потом к нам." Так что я забил. Лучше в какой-нибудь foundation подамся.
