### ISSUE TITLE
Run in Docker environment

### ISSUE THREAD

**Issue by binakot** [TyVik/geopuzzle#18]
It's a really good idea to run all this stuff with Docker. 
We can use docker-compose or even docker-stack to run this awesome project in Swarm cluster 😃 
I start to work on that issue asap. Be ready to check my PR :octocat:

**Comment by binakot** [comment]
Does the contribution guide exist? Can I start to work from master branch?

**Comment by TyVik** [comment]
It's awesome! It's task free for contribute.
