### ISSUE TITLE
What about other map projections? 🌎

### ISSUE THREAD

**Issue by binakot** [TyVik/geopuzzle#2]
[Mercator projection](https://en.wikipedia.org/wiki/Mercator_projection) is too easy :neckbeard:

What about [others](https://en.wikipedia.org/wiki/List_of_map_projections)?

For example, [Peirce quincuncial projection](https://en.wikipedia.org/wiki/Peirce_quincuncial_projection) ;)

**Comment by TyVik** [comment]
The goal of project is support to learn political map, not connecting various projection. You may fork it and add support for another map toolbox.
