### ISSUE TITLE
Clear boilerplate

### ISSUE THREAD

**Issue by TyVik** [TyVik/geopuzzle#251]
https://github.com/TyVik/geopuzzle/blob/7abd23cac1995dd5366a38ea9e79e4cf700e100a/frontend/workshop/index.jsx#L55

**Comment by ri-tae-ka** [comment]
Hey @TyVik !
Can you explain what needs to be done here, i'd like to work in this issue.

**Comment by TyVik** [comment]
I'm sorry. This task has 2 years old and I already forgot what I want to fix.
