### ISSUE TITLE
Washington DC Flag

### ISSUE THREAD

**Issue by UniversityOfPi** [TyVik/geopuzzle#268]
It looks like it's trying to pull [a non image](https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_Washington%2C_D.C..svg) when it should be pulling [this](https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_the_District_of_Columbia.svg)

I don't know how the dataset is generated, but that's what [the wikipedia article](https://en.wikipedia.org/wiki/Washington,_D.C.) uses

**Comment by TyVik** [comment]
Yes, thanks a lot for the report! I got the data for the infoboxes from Wikipedia about a year ago. Something could become obsolete. I've fixed it.
