### ISSUE TITLE
Review texts

### ISSUE THREAD

**Issue by TyVik** [TyVik/geopuzzle#722]
My English is not so good, so I welcome native speakers to update texts in 2 files:
- https://github.com/TyVik/geopuzzle/blob/develop/locale/ru/LC_MESSAGES/django.po - just fix text on English, do not touch on Russian
- https://github.com/TyVik/geopuzzle/blob/develop/frontend/locale/en.json

**Comment by atom19-i** [comment]
Hi @TyVik , can i work on this?

**Comment by TyVik** [comment]
Yep, sure

**Comment by atom19-i** [comment]
@TyVik please review my PR #729. I haven't changed any other files but some tests still failed

**Comment by TyVik** [comment]
@atom19-i I suppose the label "hacktoberfest-accepted" is valid only for PR, but I set to this issue too. Just to play it safe.

**Comment by atom19-i** [comment]
@TyVik yes, i found that you have given PR the label and that's why i deleted my comment. really sorry to be a bother..
